config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'welcome/index'

	root 'welcome#index'
	
	
	resources :users do
		collection do
			match 'login', to: 'users#login', via: [:get, :post]
			match 'logout', to: 'users#logout', via: [:get, :post]
		end
	end
	

	resources :notes do
		collection do
			match 'hello', to: 'notes#hello', via: [:get, :post]
		end
	end
	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	
  belongs_to	:user	
  has_and_belongs_to_many	:note_tags
	
  validates :header, :text, presence: true	
	
end

app/models/note_tag.rb
class NoteTag < ActiveRecord::Base

	has_and_belongs_to_many	:notes
	
end

app/models/user.rb
class User < ActiveRecord::Base

	belongs_to	:user_role
	has_many		:notes	
	
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base

	has_many	:users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action	:set_locale




  def user_init?
    @user = User.find_by(id: session[:user_id])
    if @user.nil?
      redirect_to '/users/login'
      return false
    end
    return true    		
  end  

  def set_locale
    I18n.locale = :ru
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :user_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :user_init?

  def hello
    if params[:date].nil?
      @date_filter = DateTime.now
    else
      @date_filter = (params[:date][:year] + '-' + params[:date][:month] + '-' + params[:date][:day]).to_date
    end
      @notes = Note.where("user_id = ? AND date >= ?", @user.id, @date_filter).order(date: :desc)
      respond_to do |format|
      format.js { }
    end
  end 

  def show
    @note = Note.find(params.require(:id))
    @note_tags = NoteTag.all
  end

  def index    
    @notes = Note.where(user_id: @user.id).order(date: :desc)
    @date_filter = (@notes.count > 0) ? @notes.last.date : DateTime.now
  end
  
  def new
    @note = Note.new
    @note_tags = NoteTag.all 
    @operation_description = "Новая заметка" 
  end

  def create
    @note = Note.new(params.require(:note).permit(:header, :text))
    @note.user_id = @user.id
    @note.date = DateTime.now
    
    unless params[:note_tags].nil?
      @note.note_tags = NoteTag.find(params[:note_tags]) 
    end

    @note_tags = NoteTag.all

    @note.save
    if @note.errors.empty?
      redirect_to note_path(@note)
    else
      @operation_description = "Новая заметка" 
      render 'new'
    end
  end

  def edit
    @note = Note.find(params.require(:id))
    @note_tags = NoteTag.all
    @operation_description = "Редактирование заметки" 
  end

  def update
	
    @note = Note.find(params.require(:id))
    @note_tags = NoteTag.all

    if params[:note_tags].present?
      @note.note_tags = NoteTag.find params[:note_tags]	
    else
      @note.note_tags.delete_all
    end

    @note.update_attributes(params[:note].permit(:header, :text))
    if @note.errors.empty?
      redirect_to @note
    else
      render 'show_errors'
    end
  end

  def destroy
    @note = Note.find(params.require(:id))
    @note.destroy
    redirect_to :action => :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    if session[:user_id].nil?
      if params[:user].present?
        @user = User.find_by(login: params[:user][:login], password: params[:user][:password])
        if @user.present?
          session[:user_id] = @user.id
          redirect_to '/notes'
        end
      end
    else
      redirect_to '/notes'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :controller => 'welcome', :action => 'index'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    user_init?
    if @user.present?
      session[:user_id] = @user.id
      redirect_to '/notes'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('notebook') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= t('notebook') %></h1>
<%= yield %>
</body>
</html>

app/views/notes/_date_filter.html.erb
<%= form_tag hello_notes_path, remote: true, :html => {:'data-type' => 'json'} do |f|%>
<table>
  <tr>
    <td>Фильтр</td>
    <td>
			<%= select_day @date_filter.day %>
			<%= select_month @date_filter.month %>
			<%= select_year @date_filter.year %>
    </td>
    <td>
      <%= submit_tag 'Обновить данные' %>
    </td>
  </tr>
</table>
<%end%>

app/views/notes/_note_edit.html.erb
<%= form_for @note do |f|%>
<table class="tableNote">
  <tr>
	 <th colspan="2"><%=@operation_description%></th>
  </tr>
  <tr>
    <td>Тема</td>
    <td><%= f.text_field :header, class: 'textWidth100' %></td>
  </tr>
  <tr>
    <td>Текст</td>
    <td><%= f.text_area :text, class: 'textWidth100' %></td>
  </tr>
	<tr>
    <td>Метки</td>
    <td>
      <% @note_tags.each do |nt|  %>
        <%= check_box_tag "note_tags[]", nt.id, @note.note_tags.exists?(nt.id) %>
        <%= nt.description  %>
      <% end %>
    </td>
  </tr>  
 </table>
 <%= f.submit "Сохранить" %>
<%end%>

app/views/notes/_note_menu.html.erb
<div style = "float: left; height: 30px;">
	<%= button_to "Главная страница", '/notes', :class => "menu_link", :method => :get%>
</div>
<div style = "float: left; height: 30px;">
	<%= button_to "Создать", '/notes/new', :class => "menu_link", :method => :get%>
</div>
<div style = "float: rigth; height: 30px;">
	<%= render partial: "user"%>
</div>
<br/>

app/views/notes/_note_show.html.erb
<table class="tableNote">
  <tr>
	 <th colspan="2">Просмотр заметки</th>
  </tr>
	<tr>
    <td>Тема</td>
    <td><%= @note.header%></td>
  </tr>
  <tr>
    <td>Текст</td>
    <td><%= @note.text%></td>
  </tr>
	<tr>
    <td>Метки</td>
    <td>
      <% @note_tags.each do |nt|  %>
        <%= check_box_tag "note_tags[]", nt.id, @note.note_tags.exists?(nt.id), disabled: true %>
        <%= nt.description  %>
      <% end %>
    </td>
  </tr> 
 </table>

app/views/notes/_notes_list.html.erb
	<table class="tableNote">
			 <tr>
			   <th colspan="5">Список заметок</th>
			 </tr>
			 <tr>
			   <th>Тема</th>
			   <th>Дата</th>
			   <th>Просмотр</th>
			   <th>Редактировать</th>
			   <th>Удалить</th>
			 </tr>
				<% @notes.each do |n|%>
					<tr>
						<td>
							<%= n.header%>
						</td>
						<td>
							<%= n.date.strftime("%d %m %Y %H:%M:%S")%>
						</td>
						<td>
							<%= link_to 'Просмотр', n%>
						</td>
						<td>
							<%= link_to 'Редактирование', edit_note_path(n), method: :get%>
						</td>
						<td>
							<%= link_to 'Удалить', n, method: :delete, data: {confirm: "Действительно удалить заметку " + n.header + "?"} %>
						</td>
					</tr>
				<%end%>
	</table>

app/views/notes/_user.html.erb
<div style="float: right; height: 30px;">
  <%= button_to "Выйти", '/users/logout', :class => "menu_link", :method => :get%>
</div>
<div style="float: right; text-align: center;line-height: 30px;  height: 30px;position: relative;">
  <%= @user.login %>
</div>

app/views/notes/destroy.html.erb
<p><%= @note.header%></p>

app/views/notes/edit.html.erb
<%= render partial: "note_menu"%>
<table width="100%">
	<%= render partial: "note_edit"%>
</table>

app/views/notes/hello.js.erb
$("#DivNoteList").html("<%=escape_javascript(render partial: 'notes_list')%>");

app/views/notes/index.html.erb
<%= render partial: 'note_menu'%>
<%= render partial: 'date_filter'%>
<div id="DivNoteList"><%= render partial: 'notes_list'%></div>

app/views/notes/new.html.erb
<%= render partial: "note_menu"%>
<table width="100%">
	<%= render partial: "note_edit"%>
</table>

app/views/notes/show.html.erb
<%= render partial: "note_menu"%>
<table width="100%">  
	<%= render partial: "note_show"%>
</table>

app/views/notes/show_errors.html.erb
 <p>Ошибки: начало</p>
 <%= @note.errors.messages %>
 <p>Ошибки: конец</p>

app/views/users/login.html.erb
<%= form_for :user do |f|%>
<table class = "tableUser">
  <tr>
    <td>
      <%= t('user') %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :login%>
    </td>
  </tr>
  <tr>
    <td>
      <%= t('password') %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.password_field :password%>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.button t('login')%>
    </td>
  </tr>	
</table>
<% end %>

app/views/users/logout.html.erb
<%= form_tag('/users/logout') do %>

<p>Здравствуйте: <%= @user.login %></p>
<%= submit_tag "Выйти" %>

<%end%>

app/views/users/show.html.erb
<p>Здесь будет основной экран записной книжки<p>

app/views/users/test.html.erb
<p>Осуществлен переход на тестовую страницу</p>

app/views/welcome/index.html.erb
<%= button_to "Войти", "/users/login", :class => "menu_link", :method => :get%>